spring:
  application:
    name: dormManagementSystem
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/dormManagementSystem
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


server:
  servlet:
    session:
      tracking-modes: cookie