name: Deploy Spring Boot Application To API Server

on:
  push:
    branches: [ "dev" ]
    tags: [ "v*.*.*" ]

# 한번에 1개의 Actions만 실행되도록 제한
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      git_ref: ${{ github.ref }}
    secrets:
      GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'main' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag is on main branch
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git branch -r --contains ${{ github.ref_name }} | grep -w 'origin/main'

      - name: Copy config files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "configs, docker-compose.yml"
          target: /home/ubuntu/backend

      - name: Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            export RELEASE_VERSION='${{ github.ref_name }}'

            export APP_SECRET='${{ secrets.APPLICATION_SECRET }}'
            export APP_SECRET_PROFILE='${{ secrets.APPLICATION_SECRET_PROFILE }}'
            export SPRING_PROFILE='${{ vars.SPRING_PROFILE }}'
            export ENV='${{ secrets.ENV }}'
            export KEYSTORE='${{ secrets.KEYSTORE }}'
            export GOOGLE_CREDENTIALS='${{ secrets.GOOGLE_CREDENTIALS }}'
            
            mkdir -p /home/ubuntu/backend
            cd /home/ubuntu/backend
            mkdir -p ./configs
            mkdir -p ./configs/ssl
            
            sed -i "s|image: ghcr.io/hyotatofrappuccino/dorm:.*|image: ghcr.io/hyotatofrappuccino/dorm:${RELEASE_VERSION#v}|g" docker-compose.yml

            echo "$APP_SECRET" | base64 --decode > ./configs/application.yml
            echo "$APP_SECRET_PROFILE" | base64 --decode > ./configs/application-$SPRING_PROFILE.yml
            echo "$ENV" | base64 --decode > ./.env
            echo "$KEYSTORE" | base64 --decode > ./configs/ssl/keystore.p12
            echo "$GOOGLE_CREDENTIALS" | base64 --decode > ./configs/credentials.json

            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f